openapi: 3.0.0
info:
  title: Recipe Book API
  version: '1.0'
  description: API documentation for the Recipe Book application
paths:
  /api/recipes/:
    get:
      summary: Get all recipes
      tags:
        - Recipes
      security:
        - ApiKeyAuth: []
      responses:
        '200':
          description: A list of recipes
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Recipe'
    post:
      summary: Create a new recipe
      tags:
        - Recipes
      security:
        - ApiKeyAuth: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Recipe'
      responses:
        '201':
          description: Recipe created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Recipe'
  /api/recipes/{id}/:
    get:
      summary: Get recipe details
      tags:
        - Recipes
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      security:
        - ApiKeyAuth: []
      responses:
        '200':
          description: Recipe details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Recipe'
    put:
      summary: Update an existing recipe
      tags:
        - Recipes
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      security:
        - ApiKeyAuth: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Recipe'
      responses:
        '200':
          description: Recipe updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Recipe'
    delete:
      summary: Delete a recipe
      tags:
        - Recipes
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      security:
        - ApiKeyAuth: []
      responses:
        '204':
          description: Recipe deleted
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-KEY
  schemas:
    Recipe:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        title:
          type: string
        ingredients:
          type: string
        instructions:
          type: string
        cuisine:
          type: string

